# Generated by Django 5.0.6 on 2024-05-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_user_email', models.EmailField(max_length=100)),
                ('date_sent', models.DateTimeField(default='12/05/2024, 17:53:21')),
                ('message_content', models.CharField(max_length=10000)),
                ('receiver_user_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sendmessage',
            constraint=models.UniqueConstraint(fields=('sender_user_email', 'date_sent'), name='send message constraint'),
        ),
    ]
