# Generated by Django 5.0.6 on 2024-05-12 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_sendmessage_date_sent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sendmessage',
            name='send message constraint',
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 23, 9, 55)),
        ),
    ]
